### PR TITLE
add new option to only set the container's height based on the slides

### PR DESCRIPTION
**Pull request by torotil**
To have a mobile ready website we need a new configuration option to only set the container's height (instead of the height and width) automatically.

### CODE REVIEW

**Comment by torotil** [comment]
Is there any reason why this shouldn't be part of jquery cycle?

For us this is vital as only with this patch we can make responsive layouts and still use jquery-cycle.

**Comment by torotil** [comment]
I've just re-rolled the patch against the current master branch.

**Comment by malsup** [comment]
Thanks for the pull.

**Comment by torotil** [comment]
Thanks for pulling!

**Pull request merged**
